import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "@/../public/Aeroduel Placeholder.png"
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <nav className="fixed top-0 w-full bg-slate-950/80 backdrop-blur-md z-50 border-b border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center gap-2">
            <Image className="w-10 h-10" src={Logo} alt="Logo"/>
            <span className="text-xl font-bold">AERODUEL</span>
          </div>
          <div className="hidden md:flex gap-8">
            <a href="#about" className="hover:text-teal transition">About</a>
            <a href="#features" className="hover:text-teal transition">Features</a>
            <a href="#tech-stack" className="hover:text-teal transition">Tech Stack</a>
            <a href="#roadmap" className="hover:text-teal transition">Roadmap</a>
            <a href="#download" className="hover:text-teal transition">Download</a>
          </div>
        </div>
      </div>
    </nav>
  );
}

function Footer() {
  return null;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <Header />
    <main className="flex justify-center flex-col bg-background pt-14">
      {children}
    </main>
    <Footer />
    </body>
    </html>
  );
}
